apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring

spec:
  serviceName: prometheus-headless

  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      serviceAccountName: prometheus

      containers:
        - name: prometheus

          image: ghcr.io/prometheus/prometheus:v3.13.1
          imagePullPolicy: IfNotPresent

          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"

          ports:
            - containerPort: 9090
              name: http

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: 500m
              memory: 1Gi

          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090

            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090

            initialDelaySeconds: 30
            periodSeconds: 15

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus

            - name: prometheus-data
              mountPath: /prometheus

      volumes:
        - name: config
          configMap:
            name: prometheus-config
       
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
