apiVersion: v1
kind: Service

metadata:
  name: alertmanager-headless
  namespace: monitoring

spec:
  clusterIP: None

  selector:
    app: alertmanager

  ports:
    - name: http
      port: 9093
      targetPort: 9093
