apiVersion: v1
kind: Pod

metadata:
  name: log-generator

spec:
  containers:
    - name: logger
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          i=0
          while true; do
            echo "Day09-Test-$i"
            i=$((i+1))
            sleep 10
          done

      resources:
        requests:
          cpu: 20m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 32Mi

  restartPolicy: Never
